.PHONY: autoflagger h5toms wsclean rfimasker

all: autoflagger h5toms rfimasker wsclean

autoflagger:
	$(MAKE) -C autoflagger build

h5toms:
	$(MAKE) -C h5toms build

rfimasker:
	$(MAKE) -C rfimasker build

wsclean:
	$(MAKE) -C wsclean build
