#!/usr/bin/env python
"""
This is th downobs kliko file. Is is ment to be called from
inside a kliko container.
"""
from __future__ import print_function
import os
import sys
from kliko.validate import validate
import kliko
import subprocess

binary = "/usr/bin/curl"

# validate and parse the kliko arguments
parameters = validate()

os.chdir(kliko.output_path)

cmd = [binary, parameters['url']]

if 'filename' in parameters:
    cmd += ['-o', parameters['filename']]

# call
print("running: {}".format(cmd))
error = subprocess.call(cmd)
sys.exit(error)
