.PHONY: autoflagger h5toms wsclean rfimasker downobs

all: autoflagger h5toms rfimasker wsclean downobs

autoflagger:
	$(MAKE) -C autoflagger build

h5toms:
	$(MAKE) -C h5toms build

rfimasker:
	$(MAKE) -C rfimasker build

wsclean:
	$(MAKE) -C wsclean build

downobs:
	$(MAKE) -C downobs build
