#!/usr/bin/env python
"""
This is the rfimasker kliko file. Is is ment to be called from
inside a kliko container.
"""

from __future__ import print_function
import os
import sys
from glob import glob
from kliko.validate import validate
from itertools import chain
import kliko
import subprocess


binary = "/usr/bin/mask_ms.py"

# validate and parse the kliko arguments
parameters = validate()

# build list of input files
pattern = parameters.pop('pattern')
ms_files = glob(os.path.join(kliko.work_path, pattern))

# format the arguments
args = list(chain(*[["--" + k, v] for k, v in parameters.items() if v]))

# combine
cmd = [binary] + args + ms_files

print(os.listdir(kliko.param_files))

if ms_files:
    # call
    print("running: {}".format(cmd))
    error = subprocess.call(cmd)
    sys.exit(error)
else:
    print("pattern {} doesn't match any input files!".format(pattern), file=sys.stderr)
    sys.exit(1)
